org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8 -Dorg.gradle.internal.http.connectionTimeout=8000 -Dorg.gradle.internal.http.socketTimeout=10000
org.gradle.vfs.watch=false
kotlin.daemon.jvmargs=-Xmx2048m
android.useAndroidX=true
android.suppressUnsupportedCompileSdk=35
android.aapt2FromMavenOverride=/data/data/com.termux/files/usr/bin/aapt2
android.builder.sdkDownload=false
